---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: alone-christmas-site
spec:
  encryptedData:
    redis-port: AgBQHnFuYG1KKVEh85oPzwxa0deXKDkqVuaFGDMvcRwvVEuiq7tC7vrxYkehm1T2f9hB7XzN5VmRPHFkKVm6kBwFi4BQ2XE4U22ld/lGZNSrQ/2rPiOz6uLcVzN/20cVXPUkEZ7LhbQkhTcxJ4hKM4EtrqbIyqLbnDKVkcM+54ceX9C3YQ0R4JQNe1fMPpy82Kre0Z77DUpCF9VSkmTBIY0Rsg7yQTnbsizUBBJANHF2I19PsR3gJ8m5uHFj5CTcC6leRbWVmT4ewrfvSissuvmVQb6PNAuRWTOrAaoSY57cJHbLfnBKBcaE6Stc4msK4nwCOoSf/w2zz6NOBtrC3joAwDAM6O6JaS+HJI6oux5praeMTAaVAP0Jmnof3Q6CosB1mMnR36Cw0Xpzoyafte/PyM/d/LpXFiYe03S+iHICaBFLbPwkUQY1fMrdMkGqXT/zVHtCV/JGs4a4Sydm2jDERWcUkb3YNBU5xKvyMQraw1Qa32F8hMJMKMJpisbq+E1NvpxBff8/q2xuMblzl4r6QueKFtGBB550/hLdykL3P9MxjMJCOc66LdUK5bC1jFLfaXErlfqx0TIX6YaVMWeDcNnHg7fVqt/mHJisEFGx9Kx1P0lEfm7apOh22PSgDkiZDxIYgnX7SOVUy+7jGzT3OChltNQm6EJ01mpBGkDUVwjqGbbtjpD2Fw5BYobpa73yfEcE
    upstash-redis-token: AgApiA5tfFOYJOF4atpofeHYD4z9KDULIgdzjYANBV/xs5aVgdCk1PJmMZT46zMKZY3QpEbaeHVyo9+vMGr5Oe4u9vzbejmMLs7mG7w8bL6yTZVYRx+JZb1MTXb3Y3Xcsbz6HNqMQVa6/a5Wgy/6V+v3kfav07lxI5zk8b8ln0FXZtaR+BeFjmwGpB0f20yXJaTSdpsVEzV0eFJeb39q/46Y6TZ3Tjh5QLurL78fQ/lYUEIKD/Oqhu3amqgv4iiL+/QtudzsnfXCnpu1BEPBWrdKrdhQ4/fGUszWTEflLBImKlD2AkS5O0WWH0O1vYPE4FmSXeHMjy1IlWAQGOPx4T3BPtpjTkJCclKiIT5UT/2s5icMq52e+VY5/tDV2ysjkoTyIb9eWwvgG3z+MlKYk51fjdg2uYgWlMQUJHiznFkCmTYmuTkGNA8cSp19UjvJSxqlT8obHvwcmqUX8XR1hgDMqPWd15DDc+Nu5ymkKvL7S+5CDBhhs2Sux9V26J2QdIuCzd14Ij+wVhPikJfbC5JycX4MlzMlI4f7hP+ALvljfApX85VfDDMXOxQI8v3yqq9AUO3CPtzW5hWxEavJS3j/gyeCAFSXlVTq+Bg5RqVoPr5FVxwE+sOYDZFwuhupYHYclcqe39GQ2P2B1nIH3ZJYIZDpfc4LZMb+aKFiSNG6iinOyDWsiJMG6SS8n8CL6LT/0iVUrnMxj6g5YD5h29/7q4Hk
  template:
    metadata:
      name: redis-secret
      namespace: alone-christmas-site
    type: Opaque
